// 🚫 Do not import this file directly. Use `types/index.ts` instead.
import {
  IsArray,
  IsBoolean,
  IsEnum,
  IsISO8601,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested
} from 'class-validator';
import { IsCiString } from './custom_validators/ciString';
import { Type } from 'class-transformer';
import { IsCountryCode } from './custom_validators/countryCode';
import { ProfileTypeEnum } from './ocpi-session.dto';
import { DisplayTextDto } from './ocpi-evse.dto';

export enum AllowedTypeEnum {
  ALLOWED = 'ALLOWED',
  BLOCKED = 'BLOCKED',
  EXPIRED = 'EXPIRED',
  NO_CREDIT = 'NO_CREDIT',
  NOT_ALLOWED = 'NOT_ALLOWED'
}

export enum TokenTypeEnum {
  AD_HOC_USER = 'AD_HOC_USER', // One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a  customer, probably an app user.
  APP_USER = 'APP_USER', // Token ID generated by a server (or App.) to identify a user of an App. The same user uses the same Token for every Session.
  OTHER = 'OTHER', // Other type of tokens
  RFID = 'RFID' // RFID Token
}

export enum WhitelistTypeEnum {
  ALWAYS = 'ALWAYS', // Token always has to be whitelisted, realtime authorization is not possible/allowed. CPO shall always allow any use of this Token.
  ALLOWED = 'ALLOWED', //It is allowed to whitelist the token, realtime authorization is also allowed. The CPO may choose which version of authorization to use.
  ALLOWED_OFFLINE = 'ALLOWED_OFFLINE', // In normal situations realtime authorization shall be used. But when the CPO cannot get a response from the eMSP (communication between CPO and eMSP is offline), the CPO shall allow this Token to be used.
  NEVER = 'NEVER' // Whitelisting is forbidden, only realtime authorization is allowed. CPO shall always send a realtime authorization for any use of this Token to the eMSP.
}

export class LocationReferencesDto {
  /**
   * Unique identifier for the location.
   */
  @IsNotEmpty()
  @IsString()
  @IsCiString({ message: 'Value must be a valid CI string' })
  @MaxLength(36)
  location_id: string;

  /**
   * Unique identifiers for EVSEs within the CPO’s platform for the EVSE
   * within the given location.
   */
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  @IsCiString({ each: true, message: 'Value must be a valid CI string' })
  @MaxLength(36, { each: true })
  evse_uids?: string[];
}

export class EnergyContractDto {
  /**
   * Name of the energy supplier for this token.
   */
  @IsNotEmpty()
  @MaxLength(64)
  supplier_name: string;

  /**
   * Contract ID at the energy supplier, that belongs to the owner of this token.
   */
  @IsOptional()
  @MaxLength(64)
  contract_id?: string;
}

export class TokenDto {
  @IsNotEmpty()
  @IsCiString({ message: 'Value must be a valid CI string' })
  @MaxLength(2)
  @IsCountryCode({ message: 'country_code is not valid' })
  country_code: string; // ISO-3166 alpha-2 country code of the MSP that 'owns' this Token.

  @IsNotEmpty()
  @IsCiString({ message: 'Value must be a valid CI string' })
  @MaxLength(3)
  party_id: string; // ID of the eMSP that 'owns' this Token (following the ISO-15118 standard).

  /**
   * Unique ID by which this Token, combined with the Token type, can be identified.
   * This is the field used by CPO system (RFID reader on the Charge Point) to
   * identify this token.
   * Currently, in most cases: type=RFID, this is the RFID hidden ID as read by the
   * RFID reader, but that is not a requirement.
   * If this is a APP_USER or AD_HOC_USER Token, it will be a uniquely, by the eMSP,
   * generated ID.
   * This field is named uid instead of id to prevent confusion with: contract_id.
   */
  @IsNotEmpty({ message: 'uid is required' })
  @IsString()
  @MaxLength(36)
  uid: string;

  /**
   * Type of the token
   */
  @IsOptional()
  @IsEnum(TokenTypeEnum)
  type?: TokenTypeEnum = TokenTypeEnum.RFID;

  /**
   * Uniquely identifies the EV Driver contract token within the eMSP’s platform (and
   * suboperator platforms). Recommended to follow the specification for eMA ID
   * from "eMI3 standard version V1.0" (http://emi3group.com/documents-links/)
   * "Part 2: business objects."
   */
  @IsNotEmpty()
  @IsCiString({ message: 'Value must be a valid CI string' })
  @MaxLength(36)
  contract_id: string;

  /**
   * Visual readable number/identification as printed on the Token (RFID card), might
   * be equal to the contract_id.
   */
  @IsOptional()
  @IsString()
  @MaxLength(64)
  visual_number?: string;

  /**
   * Issuing company, most of the times the name of the company printed on the
   * token (RFID card), not necessarily the eMSP.
   */
  @IsString()
  @MaxLength(64)
  issuer: string;

  /**
   * This ID groups a couple of tokens. This can be used to make two or more
   * tokens work as one, so that a session can be started with one token and
   * stopped with another, handy when a card and key-fob are given to the EV-driver.
   * Beware that OCPP 1.5/1.6 only support group_ids (it is called parentId in OCPP
   * 1.5/1.6) with a maximum length of 20.
   */
  @IsOptional()
  @IsString()
  @MaxLength(36)
  group_id?: string;

  /**
   * Is this Token valid
   */
  @IsBoolean()
  valid: boolean;

  /**
   * Indicates what type of white-listing is allowed.
   */
  @IsEnum(WhitelistTypeEnum)
  whitelist: WhitelistTypeEnum;

  /**
   * Language Code ISO 639-1. This optional field indicates the Token owner’s
   * preferred interface language. If the language is not provided or not supported
   * then the CPO is free to choose its own language.
   */
  @IsOptional()
  @IsString()
  @MaxLength(2)
  language?: string;

  /**
   * The default Charging Preference. When this is provided, and a charging session
   * is started on an Charge Point that support Preference base Smart Charging and
   * support this ProfileType, the Charge Point can start using this ProfileType,
   * without this having to be set via: Set Charging Preferences.
   */
  @IsOptional()
  @IsEnum(ProfileTypeEnum)
  default_profile_type?: ProfileTypeEnum;

  /**
   * When the Charge Point supports using your own energy supplier/contract at a
   * Charge Point, information about the energy supplier/contract is needed so the
   * CPO knows which energy supplier to use.
   * NOTE: In a lot of countries it is currently not allowed/possible to use a drivers
   * own energy supplier/contract at a Charge Point.
   */
  @IsOptional()
  @ValidateNested()
  @Type(() => EnergyContractDto)
  energy_contract?: EnergyContractDto;

  /**
   * Timestamp when this Token was last updated (or created).
   */
  @IsNotEmpty({ message: 'last_updated is required' })
  @IsISO8601({ strict: true }) // Ensures string is in correct UTC format
  last_updated: string;
}

export class AuthorizationInfoDto {
  /**
   * Status of the Token, and whether charging is allowed at the
   * optionally given location.
   */
  @IsNotEmpty()
  @IsEnum(AllowedTypeEnum)
  allowed: AllowedTypeEnum;

  /**
   * The complete Token object for which this authorization was
   * requested.
   */
  @IsNotEmpty()
  @ValidateNested()
  @Type(() => TokenDto)
  token: TokenDto;

  /**
   * Optional reference to the location if it was included in the
   * request, and if the EV driver is allowed to charge at that
   * location. Only the EVSEs the EV driver is allowed to charge at
   * are returned.
   */
  @IsOptional()
  @ValidateNested()
  @Type(() => LocationReferencesDto)
  location?: LocationReferencesDto;

  /**
   * Reference to the authorization given by the eMSP, when given,
   * this reference will be provided in the relevant Session and/or
   * CDR.
   */
  @IsOptional()
  @IsString()
  @IsCiString({ message: 'Value must be a valid CI string' })
  @MaxLength(36)
  authorization_reference?: string;

  /**
   * Optional display text, additional information to the EV driver.
   */
  @IsOptional()
  @ValidateNested()
  @Type(() => DisplayTextDto)
  info?: DisplayTextDto;
}
